"""initial schema

Revision ID: 78df404e67dc
Revises: 
Create Date: 2026-09-05 21:06:51.234992
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '78df404e67dc'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concepts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('difficulty_prior', sa.Float(), nullable=False),
    sa.Column('bkt_prior', sa.Float(), nullable=False),
    sa.Column('bkt_learn', sa.Float(), nullable=False),
    sa.Column('bkt_slip', sa.Float(), nullable=False),
    sa.Column('bkt_guess', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['concepts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('cohort_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('anomaly_flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.Float(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('anomaly_flags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_anomaly_flags_user_id'), ['user_id'], unique=False)

    op.create_table('mastery_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('concept_id', sa.Integer(), nullable=False),
    sa.Column('mastery_prob', sa.Float(), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mastery_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mastery_snapshots_concept_id'), ['concept_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mastery_snapshots_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_mastery_user_concept_time', ['user_id', 'concept_id', 'created_at'], unique=False)

    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('concept_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('correct_answer', sa.String(length=255), nullable=False),
    sa.Column('irt_difficulty', sa.Float(), nullable=False),
    sa.Column('irt_discrimination', sa.Float(), nullable=False),
    sa.Column('p_value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_questions_concept_id'), ['concept_id'], unique=False)

    op.create_table('sessions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('questions_attempted', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('concept_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('response_time_ms', sa.Integer(), nullable=False),
    sa.Column('hints_used', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attempts_concept_id'), ['concept_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attempts_question_id'), ['question_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attempts_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_attempts_user_time', ['user_id', 'created_at'], unique=False)

    op.create_table('predictions_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('policy', sa.String(length=50), nullable=False),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('predicted_prob', sa.Float(), nullable=False),
    sa.Column('actual_outcome', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('predictions_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_predictions_log_model_version'), ['model_version'], unique=False)
        batch_op.create_index(batch_op.f('ix_predictions_log_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('predictions_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_predictions_log_user_id'))
        batch_op.drop_index(batch_op.f('ix_predictions_log_model_version'))

    op.drop_table('predictions_log')
    with op.batch_alter_table('attempts', schema=None) as batch_op:
        batch_op.drop_index('ix_attempts_user_time')
        batch_op.drop_index(batch_op.f('ix_attempts_user_id'))
        batch_op.drop_index(batch_op.f('ix_attempts_question_id'))
        batch_op.drop_index(batch_op.f('ix_attempts_concept_id'))

    op.drop_table('attempts')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_user_id'))

    op.drop_table('sessions')
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_questions_concept_id'))

    op.drop_table('questions')
    with op.batch_alter_table('mastery_snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_mastery_user_concept_time')
        batch_op.drop_index(batch_op.f('ix_mastery_snapshots_user_id'))
        batch_op.drop_index(batch_op.f('ix_mastery_snapshots_concept_id'))

    op.drop_table('mastery_snapshots')
    with op.batch_alter_table('anomaly_flags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_anomaly_flags_user_id'))

    op.drop_table('anomaly_flags')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('concepts')
    # ### end Alembic commands ###
